import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Loading from "./loading";
import MainRoot from "../ui/MainRoot";
import NavBar from "../ui/layout/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainRoot>
          <NavBar/>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </MainRoot>
      </body>
    </html>
  );
}
